linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  gocyclo:
    #  https://groups.google.com/g/golang-nuts/c/HNNUjE5VWos
    min-complexity: 10
  dupl:
    threshold: 100
  go-const:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 150
  local-prefixes: github.com/golangci/golangci-lint



run:
  concurrency: 7
